version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-datastructures}:${IMAGE_TAG:-latest}
    volumes:
      - ../../:/workspace
    command: /bin/bash
    working_dir: /workspace
    tty: true
    stdin_open: true 